"""Export the Claude Code session transcript to a readable markdown log.

Equivalent to the interactive `/export`: it serialises the conversation
(user + assistant turns, tool calls, and tool results) from the session .jsonl
into session-log.md. Large blobs (e.g. the workflow's returned playbooks) are
truncated, but the proof of the loop is preserved: the Workflow launches, and the
returned scores / verifier systematic-errors / diagnostician playbook rewrites.

Usage: python3 harness/export_session.py <transcript.jsonl> session-log.md
"""
import json
import sys

CAP = 2200  # per-block truncation


def clip(s, cap=CAP):
    s = s if isinstance(s, str) else json.dumps(s)
    s = s.replace("\r", "")
    return s if len(s) <= cap else s[:cap] + f"\n…[+{len(s) - cap} chars truncated]"


def text_of(content):
    """Flatten a message.content (str or list of blocks) to printable parts."""
    out = []
    if isinstance(content, str):
        if content.strip():
            out.append(("text", content))
        return out
    for b in content or []:
        if not isinstance(b, dict):
            continue
        t = b.get("type")
        if t == "text" and b.get("text", "").strip():
            out.append(("text", b["text"]))
        elif t == "thinking":
            continue  # not part of the visible log
        elif t == "tool_use":
            inp = b.get("input", {})
            keys = ", ".join(f"{k}={clip(v, 160)}" for k, v in inp.items()
                             if k not in ("script",)) if isinstance(inp, dict) else clip(inp, 200)
            out.append(("tool", f"{b.get('name', '?')}({clip(keys, 600)})"))
        elif t == "tool_result":
            c = b.get("content", "")
            if isinstance(c, list):
                c = "\n".join(x.get("text", "") for x in c if isinstance(x, dict))
            proof = loop_proof(c)
            out.append(("result", proof if proof else clip(c)))
    return out


def loop_proof(text):
    """If a tool result is a workflow loop result, render a compact proof of the
    three-agent loop instead of a raw truncation: the Brier curve + per-generation
    verifier findings and diagnostician playbook rewrites."""
    if not isinstance(text, str) or '"scores"' not in text or '"playbooks"' not in text:
        return None
    s = text[text.find("{"):]
    try:
        d = json.loads(s)
    except Exception:
        return None
    if not (isinstance(d, dict) and d.get("scores") and d.get("playbooks")):
        return None
    L = ["LOOP RESULT — proof of forecast → grade → diagnose → rewrite\n",
         "Brier curve (train / holdout) by generation:"]
    for sc in d["scores"]:
        L.append(f"  gen {sc['generation']}: train {sc['train_brier']}  holdout {sc['holdout_brier']}"
                 f"  (n_train={sc['n_train']}, n_holdout={sc['n_holdout']})")
    for dg in d.get("diagnoses", []):
        L.append(f"\n— gen {dg['from_generation']} → {dg['from_generation']+1} —")
        L.append(f"  VERIFIER (isolated) train Brier: {dg.get('verifier_train_brier')}")
        for e in dg.get("verifier_systematic_errors", []):
            L.append(f"    · systematic error flagged: {clip(e, 220)}")
        for e in dg.get("errors_addressed", []):
            L.append(f"  DIAGNOSTICIAN rewrote: {clip(e, 400)}")
    # show which final-playbook rules carry generation-cited rewrites
    final = d["playbooks"][-1].get("markdown", "")
    cites = [ln.strip() for ln in final.splitlines() if "changed_gen" in ln]
    if cites:
        L.append("\nFinal playbook rules carrying generation-cited rewrites:")
        for c in cites[:6]:
            L.append("  " + clip(c, 300))
    return "\n".join(L)


def main():
    path, out_path = sys.argv[1], sys.argv[2]
    lines = []
    with open(path, errors="ignore") as f:
        for ln in f:
            ln = ln.strip()
            if not ln:
                continue
            try:
                lines.append(json.loads(ln))
            except Exception:
                pass

    md = ["# Glassbox — Session Log",
          "",
          "_Faithful export of the Claude Code session transcript that produced this "
          "repository: the self-improving forecaster loop (forecaster / isolated verifier / "
          "diagnostician), run across both domains. Generated by "
          "`harness/export_session.py` from the session `.jsonl` (equivalent to `/export`). "
          "Long tool outputs are truncated; the workflow scores, verifier findings, and "
          "diagnostician playbook rewrites are preserved as the proof the loop ran._",
          ""]

    turn = 0
    for obj in lines:
        typ = obj.get("type")
        msg = obj.get("message") or {}
        role = msg.get("role") or typ
        if role not in ("user", "assistant"):
            continue
        parts = text_of(msg.get("content"))
        if not parts:
            continue
        ts = (obj.get("timestamp") or "")[:19]
        turn += 1
        md.append(f"\n## [{turn}] {role.upper()}  ·  {ts}\n")
        for kind, body in parts:
            if kind == "text":
                md.append(clip(body, 6000))
            elif kind == "tool":
                md.append(f"\n**→ tool call:** `{body}`")
            elif kind == "result":
                md.append(f"\n<details><summary>tool result</summary>\n\n```\n{body}\n```\n</details>")
        md.append("")

    md += appendix()
    open(out_path, "w").write("\n".join(md) + "\n")
    print(f"wrote {out_path}: {turn} turns from {len(lines)} transcript records")


def appendix():
    """Self-contained proof of the loop, built from committed artifacts + the raw
    workflow subagent transcripts (which the truncated task-notifications omit)."""
    import glob
    import os
    A = ["\n\n---\n\n# Appendix — Proof the loop ran",
         "",
         "_The background workflow results are truncated in the transcript above. "
         "This appendix reconstructs the proof from committed artifacts "
         "(`data/diagnoses*.json`, `scores_by_generation*.json`) and the raw workflow "
         "subagent transcripts._", ""]

    # 1) the three distinct agents actually ran — count by role across all workflow runs
    role_markers = {
        "forecaster": "disciplined forecaster",
        "verifier (isolated)": "INDEPENDENT VERIFIER",
        "diagnostician": "DIAGNOSTICIAN",
    }
    counts = {k: 0 for k in role_markers}
    wfdirs = glob.glob(os.path.expanduser(
        "~/.claude/projects/*glassbox*/**/subagents/workflows/wf_*"), recursive=True)
    for wf in wfdirs:
        for jf in glob.glob(os.path.join(wf, "agent-*.jsonl")):
            try:
                txt = open(jf, errors="ignore").read()
            except Exception:
                continue
            for role, marker in role_markers.items():
                if marker in txt:
                    counts[role] += 1
    A.append("## The three agents")
    A.append(f"Across {len(wfdirs)} workflow run(s), distinct subagents by role "
             "(detected by the role instruction in each agent's transcript):")
    for r, n in counts.items():
        A.append(f"- **{r}** — {n} agent transcripts")
    A.append("\nThe verifier ran in an isolated context: it received only "
             "`(type, probability, outcome)` rows — never the playbook or question text.")

    # 2) per-generation grader findings + diagnostician rewrites, both domains
    for label, dpath, spath in [
        ("Domain 1 — prediction markets", "data/diagnoses.json", "scores_by_generation.json"),
        ("Domain 2 — GitHub issue closure", "data/diagnoses_github.json", "scores_by_generation_github.json"),
    ]:
        if not os.path.exists(dpath):
            continue
        A.append(f"\n## {label}")
        if os.path.exists(spath):
            sc = json.load(open(spath))
            A.append("Brier curve (train / holdout):")
            for s in sc:
                A.append(f"- gen {s['generation']}: train {s['train_brier']} · holdout {s['holdout_brier']}")
        for dg in json.load(open(dpath)):
            A.append(f"\n**gen {dg['from_generation']} → {dg['from_generation']+1}** · "
                     f"grader train Brier {dg.get('verifier_train_brier')}")
            for e in dg.get("verifier_systematic_errors", []):
                A.append(f"- grader flagged: {clip(e, 240)}")
            for e in dg.get("errors_addressed", []):
                A.append(f"- diagnostician rewrote: {clip(e, 500)}")
    A.append("\n_Full rewritten playbooks with generation-cited evidence: "
             "`playbook/gen1.md`…`gen5.md` (markets) and `playbook/github_gen1.md`…"
             "`github_gen5.md` (transfer)._")
    return A


if __name__ == "__main__":
    main()
